# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90258de24ceca0a9c51c1ec4082c7c38c04cbd1938179dd39dfc2c6130c8bad1599d98d314d78b645f839387e53e191f08020fff2e427f09532c35041dcae11b

test:
  secret_key_base: a5a656555175af07278f56f9c08bdd94242c62895b2e573e0d60dee5955f32706ceb66e73ad6376cdd91f509e6e5b9db58b0b87c79571f210952f10ca094942e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
